import { DataTypes } from "sequelize";
import sequelize from "../../config/database.js";

const Swap = sequelize.define(
  "Swap",
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    user_key: { type: DataTypes.CHAR(30) },
    account_key: { type: DataTypes.CHAR(30) },
    source_identifier: { type: DataTypes.CHAR(250) },
    target_identifier: { type: DataTypes.CHAR(250) },
    source_from_wallet_key: { type: DataTypes.CHAR(30) },
    target_to_wallet_key: { type: DataTypes.CHAR(30) },
    source_to_wallet_key: { type: DataTypes.CHAR(30) },
    target_from_wallet_key: { type: DataTypes.CHAR(30) },
    source_currency_code: { type: DataTypes.CHAR(5) },
    target_currency_code: { type: DataTypes.CHAR(5) },
    source_amount: { type: DataTypes.STRING(250) },
    target_amount: { type: DataTypes.STRING(250) },
    exchange_rate: { type: DataTypes.STRING(250) },
    source_charge: { type: DataTypes.STRING(250) },
    custom_source_charge: { type: DataTypes.STRING(250) },
    target_charge: { type: DataTypes.STRING(250) },
    custom_target_charge: { type: DataTypes.STRING(250) },
    source_vat: { type: DataTypes.STRING(250) },
    source_vat_included: { type: DataTypes.CHAR(1) },
    target_vat: { type: DataTypes.STRING(250) },
    target_vat_included: { type: DataTypes.CHAR(1) },
    source_from_reference: { type: DataTypes.CHAR(250), unique: true },
    source_to_reference: { type: DataTypes.CHAR(250), unique: true },
    target_to_reference: { type: DataTypes.CHAR(250), unique: true },
    target_from_reference: { type: DataTypes.CHAR(250), unique: true },
    status: { type: DataTypes.CHAR(20) },
    message: { type: DataTypes.TEXT },
    source_from_opening_balance: { type: DataTypes.STRING(250) },
    source_from_closing_balance: { type: DataTypes.STRING(250) },
    source_to_opening_balance: { type: DataTypes.STRING(250) },
    source_to_closing_balance: { type: DataTypes.STRING(250) },
    target_from_opening_balance: { type: DataTypes.STRING(250) },
    target_from_closing_balance: { type: DataTypes.STRING(250) },
    target_to_opening_balance: { type: DataTypes.STRING(250) },
    target_to_closing_balance: { type: DataTypes.STRING(250) },
    source: { type: DataTypes.CHAR(50) },
    reversal_reference: { type: DataTypes.CHAR(250), unique: true },
    ip_address: { type: DataTypes.CHAR(39) },
    session_id: { type: DataTypes.CHAR(30) },
    date_created: { type: DataTypes.DATE },
    date_reversed: { type: DataTypes.DATE },
    date_modified: { type: DataTypes.DATE },
  },
  { tableName: "Swaps", timestamps: false }
);

export default Swap;
