import { mysqlTable, int, char, varchar, text, datetime } from "drizzle-orm/mysql-core";

export const cryptoDeposits = mysqlTable("CryptocurrencyDeposits", {
  id: int("id").primaryKey().autoincrement(),
  wallet_key: char("wallet_key", { length: 30 }),
  recipient_address: char("recipient_address", { length: 250 }),
  sender_address: char("sender_address", { length: 250 }),
  amount: varchar("amount", { length: 250 }),
  charge: varchar("charge", { length: 250 }),
  vat: varchar("vat", { length: 250 }),
  vat_included: char("vat_included", { length: 1 }),
  settlement: varchar("settlement", { length: 250 }),
  hash: char("hash", { length: 250 }).unique(),
  deposit_reference: char("deposit_reference", { length: 250 }).unique(),
  credit_status: char("credit_status", { length: 20 }),
  opening_balance: varchar("opening_balance", { length: 250 }),
  closing_balance: varchar("closing_balance", { length: 250 }),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_modified: datetime("date_modified"),
});

export const cryptoPayouts = mysqlTable("CryptocurrencyPayouts", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }),
  account_key: char("account_key", { length: 30 }),
  source_identifier: char("source_identifier", { length: 250 }),
  source_wallet_key: char("source_wallet_key", { length: 30 }),
  source_address: char("source_address", { length: 250 }),
  recipient_address: char("recipient_address", { length: 250 }),
  asset: char("asset", { length: 20 }),
  network: char("network", { length: 50 }),
  amount: varchar("amount", { length: 250 }),
  charge: varchar("charge", { length: 250 }),
  custom_charge: varchar("custom_charge", { length: 250 }),
  vat: varchar("vat", { length: 250 }),
  vat_included: char("vat_included", { length: 1 }),
  hash: text("hash"),
  live_reference: char("live_reference", { length: 250 }).unique(),
  isvs_reference: char("isvs_reference", { length: 250 }).unique(),
  reversal_reference: char("reversal_reference", { length: 250 }).unique(),
  vendor_reference: char("vendor_reference", { length: 250 }).unique(),
  vendor_wallet_id: char("vendor_wallet_id", { length: 250 }),
  vendor_asset_id: char("vendor_asset_id", { length: 250 }),
  vendor_response: text("vendor_response"),
  vendor: char("vendor", { length: 50 }),
  debit_status: char("debit_status", { length: 20 }),
  opening_balance: varchar("opening_balance", { length: 250 }),
  closing_balance: varchar("closing_balance", { length: 250 }),
  payout_status: char("payout_status", { length: 20 }),
  payout_response: text("payout_response"),
  tsq_response: text("tsq_response"),
  source: char("source", { length: 50 }),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_reversed: datetime("date_reversed"),
  date_modified: datetime("date_modified"),
});
