import { mysqlTable, int, char, varchar, double, datetime } from "drizzle-orm/mysql-core";

export const customSaaSDepositFees = mysqlTable("CustomSaaSDepositFees", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }).notNull(),
  account_key: char("account_key", { length: 30 }).notNull(),
  method: char("method", { length: 50 }).notNull(),
  currency_code: char("currency_code", { length: 5 }).notNull(),
  charge_value: varchar("charge_value", { length: 250 }).notNull().default("0.00"),
  charge_percentage: double("charge_percentage").notNull().default(0.0),
  charge_cap: varchar("charge_cap", { length: 250 }).notNull().default("0.00"),
  vat_include: char("vat_include", { length: 1 }).notNull().default("N"),
  identifier: char("identifier", { length: 250 }).notNull().unique(),
  is_enabled: char("is_enabled", { length: 1 }).notNull().default("Y"),
  ip_address: char("ip_address", { length: 39 }).notNull(),
  session_id: char("session_id", { length: 30 }).notNull(),
  date_created: datetime("date_created").notNull(),
  date_modified: datetime("date_modified"),
});

export const customSaaSPayoutFees = mysqlTable("CustomSaaSPayoutFees", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }),
  account_key: char("account_key", { length: 30 }),
  method: char("method", { length: 50 }),
  currency_code: char("currency_code", { length: 5 }),
  charge_value: varchar("charge_value", { length: 250 }),
  charge_percentage: double("charge_percentage"),
  charge_cap: varchar("charge_cap", { length: 250 }),
  vat_include: char("vat_include", { length: 1 }).notNull().default("N"),
  identifier: char("identifier", { length: 250 }),
  is_enabled: char("is_enabled", { length: 1 }),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_modified: datetime("date_modified"),
});

export const customSaaSSwapFees = mysqlTable("CustomSaaSSwapFees", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }),
  account_key: char("account_key", { length: 30 }),
  currency_code: char("currency_code", { length: 5 }),
  charge_value: varchar("charge_value", { length: 250 }),
  charge_percentage: varchar("charge_percentage", { length: 250 }),
  charge_cap: varchar("charge_cap", { length: 250 }),
  vat_include: char("vat_include", { length: 1 }).notNull().default("N"),
  identifier: char("identifier", { length: 250 }).unique(),
  ip_address: char("ip_address", { length: 39 }).notNull(),
  session_id: char("session_id", { length: 30 }).notNull(),
  is_enabled: char("is_enabled", { length: 1 }).default("Y"),
  date_created: datetime("date_created"),
  date_modified: datetime("date_modified"),
});

export const customSaaSTransferFees = mysqlTable("CustomSaaSTransferFees", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }),
  account_key: char("account_key", { length: 30 }),
  currency_code: char("currency_code", { length: 5 }),
  sender_charge_value: varchar("sender_charge_value", { length: 250 }),
  sender_charge_percentage: varchar("sender_charge_percentage", { length: 250 }),
  sender_charge_cap: varchar("sender_charge_cap", { length: 250 }),
  sender_vat_include: char("sender_vat_include", { length: 1 }).notNull().default("N"),
  recipient_charge_value: varchar("recipient_charge_value", { length: 250 }),
  recipient_charge_percentage: varchar("recipient_charge_percentage", { length: 250 }),
  recipient_charge_cap: varchar("recipient_charge_cap", { length: 250 }),
  recipient_vat_include: char("recipient_vat_include", { length: 1 }).notNull().default("N"),
  identifier: char("identifier", { length: 250 }).unique(),
  ip_address: char("ip_address", { length: 39 }).notNull(),
  session_id: char("session_id", { length: 30 }).notNull(),
  is_enabled: char("is_enabled", { length: 1 }).default("Y"),
  date_created: datetime("date_created"),
  date_modified: datetime("date_modified"),
});

export const customSaaSWithdrawalFees = mysqlTable("CustomSaaSWithdrawalFees", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }).notNull(),
  account_key: char("account_key", { length: 30 }).notNull(),
  currency_code: char("currency_code", { length: 5 }).notNull(),
  charge_value: varchar("charge_value", { length: 250 }).notNull().default("0.00"),
  charge_percentage: double("charge_percentage").notNull().default(0.0),
  charge_cap: varchar("charge_cap", { length: 250 }).notNull().default("0.00"),
  vat_include: char("vat_include", { length: 1 }).notNull().default("N"),
  identifier: char("identifier", { length: 250 }).notNull().unique(),
  is_enabled: char("is_enabled", { length: 1 }).notNull().default("Y"),
  ip_address: char("ip_address", { length: 39 }).notNull(),
  session_id: char("session_id", { length: 30 }).notNull(),
  date_created: datetime("date_created").notNull(),
  date_modified: datetime("date_modified"),
});
