import { mysqlTable, int, char, text, datetime } from "drizzle-orm/mysql-core";

export const customers = mysqlTable("Customers", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }),
  account_key: char("account_key", { length: 30 }),
  identifier: char("identifier", { length: 250 }).unique(),
  parent_identifier: char("parent_identifier", { length: 250 }),
  parent_reference: char("parent_reference", { length: 250 }),
  reference: char("reference", { length: 250 }).unique(),
  environment: char("environment", { length: 10 }),
  type: char("type", { length: 50 }),
  country_name: char("country_name", { length: 100 }),
  country_code: char("country_code", { length: 3 }),
  currency_code: char("currency_code", { length: 5 }),
  first_name: char("first_name", { length: 50 }),
  middle_name: char("middle_name", { length: 50 }),
  surname: char("surname", { length: 50 }),
  phone_number: char("phone_number", { length: 30 }),
  email_address: char("email_address", { length: 100 }),
  date_of_birth: char("date_of_birth", { length: 10 }),
  nationality: char("nationality", { length: 100 }),
  nationality_code: char("nationality_code", { length: 3 }),
  business_name: char("business_name", { length: 100 }),
  business_registration_number: char("business_registration_number", { length: 50 }),
  state: char("state", { length: 50 }),
  city: char("city", { length: 50 }),
  address: text("address"),
  tier: int("tier"),
  is_personal_compliant: char("is_personal_compliant", { length: 1 }),
  is_business_compliant: char("is_business_compliant", { length: 1 }),
  is_pnd: char("is_pnd", { length: 1 }),
  is_pnc: char("is_pnc", { length: 1 }),
  status: char("status", { length: 10 }),
  source: char("source", { length: 50 }),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_modified: datetime("date_modified"),
});

export const customerWallets = mysqlTable("CustomerWallets", {
  id: int("id").primaryKey().autoincrement(),
  identifier: char("identifier", { length: 250 }),
  environment: char("environment", { length: 10 }),
  wallet_key: char("wallet_key", { length: 30 }).unique(),
  wallet_id: char("wallet_id", { length: 250 }).unique(),
  charge_ledger_key: char("charge_ledger_key", { length: 30 }).unique(),
  vat_ledger_key: char("vat_ledger_key", { length: 30 }).unique(),
  reference: char("reference", { length: 30 }).unique(),
  currency_code: char("currency_code", { length: 5 }),
  source: char("source", { length: 50 }),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_modified: datetime("date_modified"),
});
