import { mysqlTable, int, char, varchar, text, datetime } from "drizzle-orm/mysql-core";

export const ngnDeposits = mysqlTable("NGNDeposits", {
  id: int("id").primaryKey().autoincrement(),
  wallet_key: char("wallet_key", { length: 30 }),
  recipient_account_number: char("recipient_account_number", { length: 10 }),
  sender_bank_name: char("sender_bank_name", { length: 100 }),
  sender_account_name: char("sender_account_name", { length: 100 }),
  sender_account_number: char("sender_account_number", { length: 10 }),
  amount: varchar("amount", { length: 250 }),
  charge: varchar("charge", { length: 250 }),
  vat: varchar("vat", { length: 250 }),
  vat_included: char("vat_included", { length: 1 }),
  stamp_duty: varchar("stamp_duty", { length: 250 }),
  settlement: varchar("settlement", { length: 250 }),
  deposit_reference: char("deposit_reference", { length: 250 }).unique(),
  stamp_duty_reference: char("stamp_duty_reference", { length: 250 }).unique(),
  stamp_duty_status: char("stamp_duty_status", { length: 20 }),
  stamp_duty_response: text("stamp_duty_response"),
  credit_status: char("credit_status", { length: 20 }),
  opening_balance: varchar("opening_balance", { length: 250 }),
  closing_balance: varchar("closing_balance", { length: 250 }),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_modified: datetime("date_modified"),
});

export const ngnPayouts = mysqlTable("NGNPayouts", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }),
  account_key: char("account_key", { length: 30 }),
  source_identifier: char("source_identifier", { length: 250 }),
  source_wallet_key: char("source_wallet_key", { length: 30 }),
  source_account_name: char("source_account_name", { length: 100 }),
  source_account_number: char("source_account_number", { length: 10 }),
  recipient_account_number: char("recipient_account_number", { length: 10 }),
  recipient_account_name: char("recipient_account_name", { length: 100 }),
  recipient_institution_name: char("recipient_institution_name", { length: 100 }),
  recipient_institution_identifier: char("recipient_institution_identifier", { length: 250 }),
  amount: varchar("amount", { length: 250 }),
  charge: varchar("charge", { length: 250 }),
  custom_charge: varchar("custom_charge", { length: 250 }),
  vat: varchar("vat", { length: 250 }),
  vat_included: char("vat_included", { length: 1 }),
  narration: char("narration", { length: 250 }),
  live_reference: char("live_reference", { length: 250 }).unique(),
  isvs_reference: char("isvs_reference", { length: 250 }).unique(),
  reversal_reference: char("reversal_reference", { length: 250 }).unique(),
  vendor_reference: char("vendor_reference", { length: 250 }).unique(),
  vendor: char("vendor", { length: 50 }),
  debit_status: char("debit_status", { length: 20 }),
  opening_balance: varchar("opening_balance", { length: 250 }),
  closing_balance: varchar("closing_balance", { length: 250 }),
  payout_status: char("payout_status", { length: 20 }),
  payout_response: text("payout_response"),
  tsq_response: text("tsq_response"),
  source: char("source", { length: 50 }),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_reversed: datetime("date_reversed"),
  date_modified: datetime("date_modified"),
});
