import { mysqlTable, int, char, varchar, text, datetime } from "drizzle-orm/mysql-core";

export const deposits = mysqlTable("Deposits", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }),
  account_key: char("account_key", { length: 30 }),
  target_identifier: char("target_identifier", { length: 250 }),
  source_wallet_key: char("source_wallet_key", { length: 30 }),
  target_wallet_key: char("target_wallet_key", { length: 30 }),
  currency_code: char("currency_code", { length: 5 }),
  amount: varchar("amount", { length: 250 }),
  charge: varchar("charge", { length: 250 }),
  vat: varchar("vat", { length: 250 }),
  status: char("status", { length: 20 }),
  message: text("message"),
  source_reference: char("source_reference", { length: 250 }).unique(),
  target_reference: char("target_reference", { length: 250 }).unique(),
  source: char("source", { length: 50 }),
  source_opening_balance: varchar("source_opening_balance", { length: 250 }),
  source_closing_balance: varchar("source_closing_balance", { length: 250 }),
  target_opening_balance: varchar("target_opening_balance", { length: 250 }),
  target_closing_balance: varchar("target_closing_balance", { length: 250 }),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_modified: datetime("date_modified"),
});

export const withdrawals = mysqlTable("Withdrawals", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }),
  account_key: char("account_key", { length: 30 }),
  source_identifier: char("source_identifier", { length: 250 }),
  source_wallet_key: char("source_wallet_key", { length: 30 }),
  target_wallet_key: char("target_wallet_key", { length: 30 }),
  currency_code: char("currency_code", { length: 5 }),
  amount: varchar("amount", { length: 250 }),
  source_charge: varchar("source_charge", { length: 250 }),
  custom_source_charge: varchar("custom_source_charge", { length: 250 }),
  target_charge: varchar("target_charge", { length: 250 }),
  source_vat: varchar("source_vat", { length: 250 }),
  source_vat_included: char("source_vat_included", { length: 1 }),
  target_vat: varchar("target_vat", { length: 250 }),
  target_vat_included: char("target_vat_included", { length: 1 }),
  status: char("status", { length: 20 }),
  message: text("message"),
  source_reference: char("source_reference", { length: 250 }).unique(),
  target_reference: char("target_reference", { length: 250 }).unique(),
  reversal_reference: char("reversal_reference", { length: 250 }).unique(),
  source_opening_balance: varchar("source_opening_balance", { length: 250 }),
  source_closing_balance: varchar("source_closing_balance", { length: 250 }),
  target_opening_balance: varchar("target_opening_balance", { length: 250 }),
  target_closing_balance: varchar("target_closing_balance", { length: 250 }),
  source: char("source", { length: 50 }),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_reversed: datetime("date_reversed"),
  date_modified: datetime("date_modified"),
});

export const transfers = mysqlTable("Transfers", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }),
  account_key: char("account_key", { length: 30 }),
  source_identifier: char("source_identifier", { length: 250 }),
  target_identifier: char("target_identifier", { length: 250 }),
  source_wallet_key: char("source_wallet_key", { length: 30 }),
  target_wallet_key: char("target_wallet_key", { length: 30 }),
  currency_code: char("currency_code", { length: 5 }),
  amount: varchar("amount", { length: 250 }),
  source_charge: varchar("source_charge", { length: 250 }),
  custom_source_charge: varchar("custom_source_charge", { length: 250 }),
  target_charge: varchar("target_charge", { length: 250 }),
  custom_target_charge: varchar("custom_target_charge", { length: 250 }),
  source_vat: varchar("source_vat", { length: 250 }),
  source_vat_included: char("source_vat_included", { length: 1 }),
  target_vat: varchar("target_vat", { length: 250 }),
  target_vat_included: char("target_vat_included", { length: 1 }),
  status: char("status", { length: 20 }),
  message: text("message"),
  source_reference: char("source_reference", { length: 250 }).unique(),
  target_reference: char("target_reference", { length: 250 }).unique(),
  reversal_reference: char("reversal_reference", { length: 250 }).unique(),
  source_opening_balance: varchar("source_opening_balance", { length: 250 }),
  source_closing_balance: varchar("source_closing_balance", { length: 250 }),
  target_opening_balance: varchar("target_opening_balance", { length: 250 }),
  target_closing_balance: varchar("target_closing_balance", { length: 250 }),
  source: char("source", { length: 50 }),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_reversed: datetime("date_reversed"),
  date_modified: datetime("date_modified"),
});

export const swaps = mysqlTable("Swaps", {
  id: int("id").primaryKey().autoincrement(),
  user_key: char("user_key", { length: 30 }),
  account_key: char("account_key", { length: 30 }),
  source_identifier: char("source_identifier", { length: 250 }),
  target_identifier: char("target_identifier", { length: 250 }),
  source_from_wallet_key: char("source_from_wallet_key", { length: 30 }),
  target_to_wallet_key: char("target_to_wallet_key", { length: 30 }),
  source_to_wallet_key: char("source_to_wallet_key", { length: 30 }),
  target_from_wallet_key: char("target_from_wallet_key", { length: 30 }),
  source_currency_code: char("source_currency_code", { length: 5 }),
  target_currency_code: char("target_currency_code", { length: 5 }),
  source_amount: varchar("source_amount", { length: 250 }),
  target_amount: varchar("target_amount", { length: 250 }),
  exchange_rate: varchar("exchange_rate", { length: 250 }),
  source_charge: varchar("source_charge", { length: 250 }),
  custom_source_charge: varchar("custom_source_charge", { length: 250 }),
  target_charge: varchar("target_charge", { length: 250 }),
  custom_target_charge: varchar("custom_target_charge", { length: 250 }),
  source_vat: varchar("source_vat", { length: 250 }),
  source_vat_included: char("source_vat_included", { length: 1 }),
  target_vat: varchar("target_vat", { length: 250 }),
  target_vat_included: char("target_vat_included", { length: 1 }),
  source_from_reference: char("source_from_reference", { length: 250 }).unique(),
  source_to_reference: char("source_to_reference", { length: 250 }).unique(),
  target_to_reference: char("target_to_reference", { length: 250 }).unique(),
  target_from_reference: char("target_from_reference", { length: 250 }).unique(),
  status: char("status", { length: 20 }),
  message: text("message"),
  source_from_opening_balance: varchar("source_from_opening_balance", { length: 250 }),
  source_from_closing_balance: varchar("source_from_closing_balance", { length: 250 }),
  source_to_opening_balance: varchar("source_to_opening_balance", { length: 250 }),
  source_to_closing_balance: varchar("source_to_closing_balance", { length: 250 }),
  target_from_opening_balance: varchar("target_from_opening_balance", { length: 250 }),
  target_from_closing_balance: varchar("target_from_closing_balance", { length: 250 }),
  target_to_opening_balance: varchar("target_to_opening_balance", { length: 250 }),
  target_to_closing_balance: varchar("target_to_closing_balance", { length: 250 }),
  source: char("source", { length: 50 }),
  reversal_reference: char("reversal_reference", { length: 250 }).unique(),
  ip_address: char("ip_address", { length: 39 }),
  session_id: char("session_id", { length: 30 }),
  date_created: datetime("date_created"),
  date_reversed: datetime("date_reversed"),
  date_modified: datetime("date_modified"),
});
